### ISSUE TITLE
What's the status of this repo?

### ISSUE THREAD

**Issue by jsolum** [django-webpack/django-webpack-loader#253]
Looking through current issues, it looks like the project is moving over to Jazzband and will continue to be maintained. But there is also this comment: https://github.com/owais/django-webpack-loader/issues/238#issuecomment-705269647, that says this project is no longer maintained.  If this project is no longer maintained, could we add that to the README, just to make it more clear?

**Comment by shonin** [comment]
Hi @jsolum, I've been following this project for a couple of years, and at this point, it appears to be _mostly_ unmaintained. The maintainer has done some work to get it into a better state, but I think he needs help. 

Because of this I have created an alternative project, [django-manifest-loader](https://github.com/shonin/django-manifest-loader). I hope you'll give it a shot and let me know how it goes. I'm happy to accept pull requests, feature requests, and bug reports.

**Comment by owais** [comment]
The status is that I have no time to add new features or support for newer versions of webpack especially since I'm not using webpack or django in any projects at the moment.  

The project is currently looking for maintainers. https://github.com/django-webpack/django-webpack-loader#looking-for-maintainers

I've created a new github org (django-webpack) and transfered the projects to it. This should make it easier for me to add other contributors and slowly give them more rights eventually completely letting the community drive the project.
